### ISSUE TITLE
Kerbalism is throwing errors related to antennas, i think.

### ISSUE THREAD

**Issue by xxmortekaixx** [Kerbalism/Kerbalism#560] opened 2019-12-10 00:33 UTC
So, i have a new save that I have started recently.  Its on 1.7.3, and its heavily modified.  When I go to launch a communications satellite with a relay dish on it, the entire game crashes.  No warning popup or anything, just a hard crash to desktop. 

The reason I think it is related to Kerbalism's antenna handling has to do with the output_log file, as the end of it says that there is a stackoverflow, and following that is a bunch of KERBALISM references. (of course, ill be including the output_log file).

When I launch the exact same craft without the relay dish, i get no crash.  I also get no crash when using other antennas.  The output_log file I have attached is from me starting the game, launching with no relay dish, going back to VAB, attaching the relay dish and then attempting to launch again.

[output_log.txt](https://github.com/Kerbalism/Kerbalism/files/3942457/output_log.txt)

**Comment by xxmortekaixx** [comment] 2019-12-10 00:51
im going to try to update Kerbalism to 3.1 and see if the issue persists.

**Comment by SirMortimer** [comment] 2019-12-11 19:18
Looks like a duplicate of #439 which is fixed in 3.1.

I'll close this, please reopen if the issue persists in the latest version.

**Closed by SirMortimer** 2019-12-11 19:18 UTC
