### ISSUE TITLE
Crew/Lab configurable experiments disappear from existing vessels

### ISSUE THREAD

**Issue by jessicest** [Kerbalism/Kerbalism#767] opened 2021-10-31 01:10 UTC
The problem: Crafts in flight sometimes lose all of their lab experiments (CHILLED/JAMMED/etc) and their Crew experiments (FLOAT/FLIGHT/LEAVE/etc).

I don't yet know how to reproduce this.

It's happened at least twice in my current save, and this thread talks about a kerbalism game in which the same issue is happening (search for "save file" to find multiple occurrences): https://forum.kerbalspaceprogram.com/index.php?/topic/196959-kerbalism-space-program/

Luckily I have a backup of my KSP folder from before the issue occurred, so we can dig into the change in symptoms.

Here's an interesting point: if we compare the contents of `persistent.sfs` before and after the loss of experiments, by restricting our search to changed `cfg =` lines in the vessel called `t6c wax tadpole`, something specific has happened:

before:

```
					cfg = "$None%LEAVE
					cfg = "$None&FLIGHT
					cfg = "$None&FLIGHT
					cfg = "$None&FLIGHT
					cfg = "%FLOAT'HERRING
					cfg = "&FLIGHT%STAKE
					cfg = "'CHILLED&JAMMED
					cfg = "8Fish Species Observation3Materials Bay Study
```

after:

```
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
```

It seems to me that the `Configure` modules all lost their configuration and reverted to scrubber/pressure mode.

KSP version (before & after): `1.12.2.3167 (WindowsPlayer x64)`
Kerbalism version (before & after): `"VERSION": {"MAJOR": 3, "MINOR": 14, "PATCH": 0, "BUILD": 0},`

Attached files from before the issue happened:

 - [installed_mods_before.txt](https://github.com/Kerbalism/Kerbalism/files/7447878/installed_mods_before.txt)
 - [persistent_before.zip](https://github.com/Kerbalism/Kerbalism/files/7447881/persistent_before.zip)

Attached files from after the issue happened (this is 21 days later; idk when it actually occurred):

 - [persistent.zip](https://github.com/Kerbalism/Kerbalism/files/7447871/persistent.zip)
 - [installed_mods_after.txt](https://github.com/Kerbalism/Kerbalism/files/7447858/installed_mods_after.txt)
 - [Player.zip](https://github.com/Kerbalism/Kerbalism/files/7447868/Player.zip) -- i assume this isn't actually useful as the issue has already occurred

I haven't actually trimmed down to minimal mods and attempted to reproduce the issue as the contributing instructions suggest; mostly because I don't know how to reproduce it! But I'm happy to attempt to reproduce it once we have some ideas of what might trigger it. My hunch is that it's from installing/uninstalling mods but that's a wild guess.

**Comment by gotmachine** [comment] 2021-10-31 08:47
Caused by a config change. Installing/uninstalling mods in an existing save will cause issues, and should be avoided.

You will notice tons of `PartModule indexing mismatch at Large.Crewed.Lab` in the log you provided.

Contrary to popular belief, KSP **isn't** able to handle correctly a part config change where modules are added/removed.
Specifically, it isn't able to "reconnect" modules to their persisted data when multiple occurences of the same module exist on a part, causing the persisted data to be either lost or assigned to the wrong module.

The only way to fix this would be to assign unique identifiers to each module in configs and to hack the stock code so it use that identifier instead of its (unreliable) module reconnection logic. Drawback being that every identifier must be manually defined in configs, which can be messy due to most Kerbalism configs being the result of multiple MM patchs.

In any case, I won't attempt to fix it in Kerbalism, this is a more general KSP issue.

**Comment by gotmachine** [comment] 2021-11-01 19:14
Duplicate of #759

**Closed by gotmachine** 2021-11-01 19:14 UTC
Labels: bug, wontfix, cfg, code
