### ISSUE TITLE
Better file manager data/sample transfer solution

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#406] opened 2019-06-05 06:25 UTC
<a href="https://github.com/SerinaTsukaya"><img src="https://avatars0.githubusercontent.com/u/9085414?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SerinaTsukaya](https://github.com/SerinaTsukaya)**
_Thursday Apr 25, 2019 at 23:34 GMT_
_Originally opened as https://github.com/SirMortimer/Kerbalism/issues/58_

----

It's a bit tricky to manage your samples as the current system is implemented. If you have a four slot Experiment storage unit and a material science bay plus a mystery goo unit, you could end up with the mystery goo being the only thing stored on in that experimental storage unit (if i understand how it works correctly) Thus, when making science return capsules, if you manage to fit the go but not the material science bay, then you have to do the material science first, store that, then run the mystery goo science in order to ensure everything ends up where it needs to be. A way it could be implimented could be similar how the crew/ship manifest mod does it, with itemized sources and destinations and with each side listing the experiment names and the amount of slots each sample takes up, with the destination one showing how many slots is left.

**Comment by SirMortimer** [comment] 2019-06-05 06:25
<a href="https://github.com/gotmachine"><img src="https://avatars1.githubusercontent.com/u/24925209?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gotmachine](https://github.com/gotmachine)**
_Friday Apr 26, 2019 at 12:24 GMT_

----

I second this, that was what I was talking about in issue #50 

My suggested solution : for each sample/data, add a "flag for transfer" button in the data window, set to false by default.
Only data/sample flagged for transfer would be transferred when the PAW "transfer data here" button is clicked.

Additionally, I suggest that in the file manager window, instead of using the black header to differentiate data and sample, data/sample is grouped by part (name of the part in the black header),
I suggest also putting the "transfer data here" button in the header instead of in the PAW.

**Comment by SirMortimer** [comment] 2019-06-05 06:25
<a href="https://github.com/SirMortimer"><img src="https://avatars2.githubusercontent.com/u/43166475?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SirMortimer](https://github.com/SirMortimer)**
_Friday Apr 26, 2019 at 15:16 GMT_

----

I'm probably not going to do that any time soon, if at all.

Currently, "transfer data" moves as much data as it can to the drive you pressed the button on. There is no ordering or sorting involved, it just moves whatever fits there. It's not ideal, but it does what it says on the tin.

> My suggested solution : for each sample/data, add a "flag for transfer" button in the data window, set to false by default. Only data/sample flagged for transfer would be transferred

My issue with this is that this would be a confusing UI for a user who doesn't know how it works. You have to open the file manager window, then click an obscure icon there, then open the PAW, click a button. Without the selection in the file manager the button wouldn't do anything.

Even if one knows how it works, it still would be a quite complicated workflow to move files/samples. I'd rather keep the current implementation.

Besides, you're not supposed to have dozens of files on dozens of drives. By the time you get into that situation, you'll have science labs. The lab should be big enough to store ALL data, it is by far the biggest hard drive in the game (except for the EVA drives, which are unlimited).

> Additionally, I suggest that in the file manager window, instead of using the black header to differentiate data and sample, data/sample is grouped by part (name of the part in the black header),
I suggest also putting the "transfer data here" button in the header instead of in the PAW.

We tried that, it doesn't work. Problem is that later in the game, you will sometimes have a dozen or more drives on your vessel. A list that groups files by parts just isn't usable any more.

**Comment by SirMortimer** [comment] 2019-06-05 06:25
<a href="https://github.com/gotmachine"><img src="https://avatars1.githubusercontent.com/u/24925209?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gotmachine](https://github.com/gotmachine)**
_Monday Apr 29, 2019 at 15:03 GMT_

----

> We tried that, it doesn't work. Problem is that later in the game, you will sometimes have a dozen or more drives on your vessel. A list that groups files by parts just isn't usable any more.

> Besides, you're not supposed to have dozens of files on dozens of drives

See my point ? Beside, empty drives could be hidden. I still think it would make a lot more sense to group files/samples per part. When you click on a part PAW button you would expect to see what is related to the part.

As for the transfer issue, well OK. Would still be nice to have at some point, even with labs I see a lot of cases when you would want to retrieve some samples and analyze others.

**Comment by gotmachine** [comment] 2019-06-22 23:07
duplicate of #411

**Closed by gotmachine** 2019-06-22 23:07 UTC
Labels: duplicate, enhancement, science
