### ISSUE TITLE
NaN EC/Science on changing SOI

### ISSUE THREAD

**Issue by Romsik788** [Kerbalism/Kerbalism#635] opened 2020-05-08 14:05 UTC
When flying to the Mun, the electricity on the ship is NaN, I also can’t collect science because of NaN. I tested only in the orbit of the Mun, in the orbit of Kerbin everything works.

**Comment by gotmachine** [comment] 2020-05-08 14:11
Send your full KSP.log found in the KSP root folder (and ideally your ModuleManager.ConfigCache found in GameData too)

**Comment by Romsik788** [comment] 2020-05-08 14:16
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4599443/KSP.log)
GameData
![temp](https://user-images.githubusercontent.com/33905242/81414457-b26aa980-914f-11ea-9f69-7a77206ba2d3.png)

**Comment by gotmachine** [comment] 2020-05-08 14:31
Well, can't find anything wrong, I fear that one will be a bit difficult to troubleshot.
Are you able to reproduce it consistently with a new vessel ?

**Comment by Romsik788** [comment] 2020-05-08 14:39
> Are you able to reproduce it consistently with a new vessel ?
Yes, this error appears on every new vessel

**Comment by Romsik788** [comment] 2020-05-08 15:16
@gotmachine Sorry, I threw off the wrong log (I didn’t fly to Mun then), please check this
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4599856/KSP.log)

**Comment by gotmachine** [comment] 2020-05-08 15:22
Ok, that make much more sense. Can you also send your persistent.sfs ?

**Comment by Romsik788** [comment] 2020-05-08 15:25
[persistent.zip](https://github.com/Kerbalism/Kerbalism/files/4599910/persistent.zip)

**Comment by gotmachine** [comment] 2020-05-08 16:06
Urgh... well... I can't find the origin of the problem...
Does it also happen with the same craft, but in a fresh save ? If you cheat everything and cheat the craft into kerbin orbit, then cheat it into mun orbit, are you able to replicate ? If so, send the log, that might help a bit more.

**Comment by Romsik788** [comment] 2020-05-08 16:13
> Does it also happen with the same craft, but in a fresh save ?

and not only with this craft. Every time I create a new game I have the this error

> If you cheat everything and cheat the craft into kerbin orbit, then cheat it into mun orbit, are you able to replicate ?

Did not quite understand the question. If I understood correctly, I did not use cheats, I built a ship from scratch and launched it to the Mun.

**Comment by gotmachine** [comment] 2020-05-08 16:15
I mean send a KSP.log where you reproduce it in fresh save (doing the minimal action for reproducing).

**Comment by Romsik788** [comment] 2020-05-08 16:16
I sent you a save, you also have this problem, or is it just me?

**Comment by gotmachine** [comment] 2020-05-08 16:27
No, I can't reproduce it. I suspect an interaction with one of the other mods you have installed, but since they are mostly visual mods that seems a bit strange.

**Comment by Romsik788** [comment] 2020-05-08 16:37
Very strange. I created a new game in sandbox mode, built the ship, entered the orbit of Kerbin, after that I went straight to the Mun and I did not meet this bug.
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4600304/KSP.log)

**Comment by gotmachine** [comment] 2020-05-08 16:40
Maybe try in career then (and sorry for requesting all this, but there isn't much more I can do on my side...)

**Comment by Romsik788** [comment] 2020-05-08 17:05
I just launched my save, and this error disappeared (not the first time), more in the log.
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4600477/KSP.log)

**Comment by Romsik788** [comment] 2020-05-08 17:31
I just figured out how to remove this bug - it is necessary to go to the space center, and through the tracking center select this ship. But I still don’t know how to reproduce this bug

**Comment by Romsik788** [comment] 2020-05-08 17:46
I created a new game in career mode, cheat money, a little science. Built a rocket and went to Mun - the bug repeated. What else can I do to help you fix it?
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4600635/KSP.log)

**Comment by gotmachine** [comment] 2020-05-08 18:12
Well I still don't understand it, but that last one was useful.
It seems somehow something goes very wrong at the exact moment the vessel undergo the Kerbin > Mun SOI transition. 
The deeper I can trace the issue is that somehow the vessel antennas data rate is being set to an incorrect value, but I fail to see how that can happen. 
But since the behavior is consistent, it has to be something (a mod) in you installation that cause it. So maybe try with a non-modded install (beside Kerbalism and dependencies) and re-add them one by one.

**Comment by Romsik788** [comment] 2020-05-08 18:39
after removing Scatterer in the new game, I did not notice bug, BUT in the old save game it was saved

**Comment by gotmachine** [comment] 2020-05-08 18:47
Scatterer it was then.
That's a bit strange but probably related to those scatterer exceptions causing some parts of KSP to freak out silently.

Regarding your existing game, once the the bug has appeared it will propagate errors in your save, doesn't matter if the source of the bug is removed or not. I highly suggest that you delete this vessel from the tracking station, otherwise the errors might propagate even more, completely corrupting your save.

**Comment by Romsik788** [comment] 2020-05-08 18:51
If I remove Scatterer then it will not be possible to play with AVE and EVE. I hope this can be fixed somehow?

**Comment by gotmachine** [comment] 2020-05-08 18:55
I will try to reproduce it with scatterer, but I suspect there is something wrong with your install, there are a lot of : 
`[ERR 20:34:27.210] [Scatterer][Error] Destroying duplicate instance, check your install for duplicate mod folders` in your log

**Comment by Romsik788** [comment] 2020-05-08 18:57
Maybe this will help somehow? https://github.com/LGhassen/Scatterer/issues/94

**Comment by gotmachine** [comment] 2020-05-08 19:24
Well, I can't reproduce it, no matter if I'm using only scatterer or scatterer + EVE + AVP.
But I'm getting the same scatterer errors as you, so they are likely unrelated to the problem. 
Frankly this is the weirdest corner case issue that I have ever seen.

**Comment by Romsik788** [comment] 2020-05-08 19:30
Can you try to install all the mods that I have?  and reproduce.

**Comment by gotmachine** [comment] 2020-05-08 19:40
Just tried that too, no luck either...

**Comment by Romsik788** [comment] 2020-05-08 19:51
I think it is mechJeb or RealPlume.  They have something to do with the rocket.  I can’t test now.

**Comment by lordcirth** [comment] 2020-05-08 21:18
Did you install scatterer from CKAN or manually? Is it possible it was installed wrong? Eg a copy nested inside itself?

**Comment by Romsik788** [comment] 2020-05-08 23:19
> Did you install scatterer from CKAN or manually?

Manually. I installed it correctly.

**Comment by Romsik788** [comment] 2020-05-09 07:02
@gotmachine I have done many tests and can confirm that the error is in Kerbalism. Here is the evidence:
GameData:
![temp](https://user-images.githubusercontent.com/33905242/81466149-f1dcd880-91d7-11ea-8e16-cea4b47e5496.png)
Screen from KSP:
![screenshot48](https://user-images.githubusercontent.com/33905242/81466220-792a4c00-91d8-11ea-97cf-22099c468f8d.png)
![screenshot49](https://user-images.githubusercontent.com/33905242/81466228-8ba48580-91d8-11ea-9aeb-68155beab2a4.png)
Log:
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4602829/KSP.log)
To trigger this bug, launch this 
[VAB.zip](https://github.com/Kerbalism/Kerbalism/files/4602835/VAB.zip)
 rocket on Mun along the following trajectory:
![screenshot50](https://user-images.githubusercontent.com/33905242/81466433-5b5de680-91da-11ea-8fc0-e0407bccb4e3.png)
Don't change anything in the rocket itself, just launch
When you fly into Mun orbit, release the kerbonaut outside the vessel and see how much EC it has, you should have a NaN value.
Reproduce it in career mode.
My save:
[persistent.zip](https://github.com/Kerbalism/Kerbalism/files/4602855/persistent.zip)
Let me know if you managed to reproduce this bug or not.

**Comment by Romsik788** [comment] 2020-05-09 09:07
I can try to reproduce this bug in the dev version. I see a lot of fix here... The truth is here https://github.com/Kerbalism/DevBuilds/releases dev versions have not been released for a long time.

**Comment by gotmachine** [comment] 2020-05-09 12:50
Yeah, problem is... I can't reproduce it it, and if it was something that was happening consistently to everyone it would have been reported many times, since a bug of that kin is likely to completely corrupt your save with NaNs, until it just crashes.
Don't bother about dev versions.

**Comment by Romsik788** [comment] 2020-05-09 13:10
I did tests every time creating a new game. The problem is not in my save game.

**Comment by gotmachine** [comment] 2020-05-09 13:29
Well just to be sure I just tried again with and without the DLCs, and EVAing (I didn't mention that earlier), still nothing.
Your save isn't of much help as things have already gone wrong in it. A save just before you enter the mun SOI would be more helpful (before the problem happen), but I have a feeling that won't change anything...
Maybe try doing a clean reinstallation of KSP. At this point it's either something that is specific to your hardware/software setup (unlikely) or a corrupted KSP installation...

**Comment by Romsik788** [comment] 2020-05-09 14:42
I reinstalled ksp and also mods but it didn’t help. I'll wait a while, maybe this bug will disappear over time.

**Comment by gotmachine** [comment] 2020-05-13 13:34
(cleaned a bunch of not very useful comments)
Another report coming from the RO discord (with ROKerbalism), user is @Arias#6364 : 

> i am in a test flight (simulate) from earth to moon, now in the influence of the moon (high space) and all my science equipment shows my in all experiments "perpetual" and no more "catching" science points.
this is just in the simulation?
in the "real" flight the experiments working there?
before i wasn't in the influence of the moon.

![image](https://user-images.githubusercontent.com/24925209/81819080-27aef380-952f-11ea-97f4-e98964031358.png)

> all experimtens worked in high space from the earth, there i also wasn't before..
i found the solution!
when i done a sim direct in the orbit of the moon all experiments work.
so it must be, because of "change of body" in simulation..

**Comment by Romsik788** [comment] 2020-05-13 15:17
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4622880/KSP.log)

**Comment by Romsik788** [comment] 2020-05-13 15:50
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4623088/KSP.log)

**Comment by gotmachine** [comment] 2020-05-13 16:45
Okay, the issue is here :
https://github.com/Kerbalism/Kerbalism/blob/00baeaf8707ee3e8cd7ebc180440685115a018ae/src/Kerbalism/Sim.cs#L133-L154
Not sure exactly which ones, but the orbit parameters can (and will) be NaN (or maybe 0) on some occasions. 

Since this code is going away in 4.0 I won't bother fixing it properly, and just implement a fallback to the old altitude based method if a NaN is detected in the return value.

**Comment by gotmachine** [comment] 2020-05-13 17:41
Fixed in c94676eae25b18d3e3ff8ede6fe44802d8688163

**Closed** 2020-05-14 16:54 UTC
Labels: bug, fix in dev
