### ISSUE TITLE
Excess dump valve of fuel cells do not dump anymore when timewarp stops

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#794] opened 2021-12-16 00:28 UTC
Difficult to explain, but after leaving timewarp a fuel cell which is set to dump excess water and nitrogen did not do so until I manually toggled through the dump settings until reaching the same state again.

This was because the automation did NOT turn on the fuel cell as the EC decreased below 20% for some reason and the battery was empty and I had to manually stop timewarp to save the souls of the remaining Kerbals.

**Comment by Gordon-Dry** [comment] 2021-12-16 01:03
https://forum.kerbalspaceprogram.com/index.php?/topic/190382-15-110-kerbalism-311/&do=findComment&comment=4065894
`I have seen a similar bug when the dump valve authomatism gets broken on reload. I reload the game, and it does not dump resources anymore. but i only have to fix it in one copy of my chemical plants and everything works afterwards. `

**Comment by gotmachine** [comment] 2022-01-16 13:35
Duplicate of #500

**Closed by gotmachine** 2022-01-16 13:35 UTC
Labels: bug, duplicate
