### ISSUE TITLE
EVA jetpacks don't refill monoprop after boarding ship + more jetpack bugs.

### ISSUE THREAD

**Issue by buczbucz** [Kerbalism/Kerbalism#811] opened 2022-04-20 11:01 UTC
Take Kerbal xxx on an EVA.

Use jetpack to fly around.

Fuel goes to 2.50/5.00 for example.

You board the ship. Click the jetpack while Kerbal xxx is on the ship. It will show 5.00/5.00 fuel.

EVA Kerbal xxx again. Jetpack fuel is back to 2.50/5.00.

Board the ship again.

Move the jetpack from kerbal xxx's inventory to ship inventory. Now it shows 2.50/5.00.

Now when you move the jetpack back to kerbal xxx it will show 2.50/5.00.

There is no way to transfer fuel between monoprop tank and the jetpack.

Moreover, if you click the jetpack while on EVA, pick it up and put it in Kerbal's xxx inventory again it will refill to 5.00/5.00. Then if you place that jetpack, while on EVA, into ship's inventory it will stay there with 5.00/5.00 fuel. Now when you board the ship with Kerbal xxx an extra jetpack will spawn on him with 2.50/5.00 fuel but the 5.00/5.00 fuel jetpack will still stay on the ship.

Finally, if you go on EVA with a full 5.00/5.00 jetpack. Fly around till it's for example 1.00/5.00 fuel. Then you click the jetpack, pick it up and place it in that kerbal's inventory again it will magically refill up to 5.00/5.00.

**It is really weird and I think it would be better to just fully refill when you board the ship without using ships monoprop like in stock ksp.**

**Comment by gotmachine** [comment] 2022-04-20 11:04
All of that is likely due to the KSP 1.12 Kerbal inventories persistence bug. Install [KSP Community Fixes](https://forum.kerbalspaceprogram.com/index.php?/topic/204002-18-112-kspcommunityfixes-bugfixes-and-qol-tweaks/).

**Comment by buczbucz** [comment] 2022-04-20 11:53
> All of that is likely due to the KSP 1.12 Kerbal inventories persistence bug. Install [KSP Community Fixes](https://forum.kerbalspaceprogram.com/index.php?/topic/204002-18-112-kspcommunityfixes-bugfixes-and-qol-tweaks/).

It's installed and was updated earlier today via ckan.

`True	False	KSP Community Fixes	Gotmachine	1.12.0	1.12.0	1.12.9	75.6 KiB	19/04/2022 09:05:40	19/04/2022 13:53:11	14,612	Fixes for stock bugs, also provides various QoL/UI improvements`

**Comment by gotmachine** [comment] 2022-04-20 11:57
Then I guess there is indeed an issue. I know there has been some changes to the stock handling since Kerbalism support for the new jetpack cargo part was introduced, something is likely broken here

**Comment by gotmachine** [comment] 2022-07-19 09:36
Did a bit of testing in KSP 1.12.3 + KSPCF 1.19 and things seems to be working as intended.
On EVAing, if the EVA pack isn't full, it is filled using the MP stored on the vessel
On boarding, if there is room on the vessel to store the MP stored in the EVA pack, the EVA pack is emptied and the MP transferred to the vessel.

The point of that system is to avoid having "stuck" MP on inventory items (EVA pack and the extra bottles). I fail to see any gameplay scenario where this behavior would be a problem.

**Comment by MarcSollie** [comment] 2022-08-13 23:36
I am still having these jetpack issue on my save, and I'm able to replicate it each time.
Using Kerbalism 3.16 with Default Config, KSP Community Fixes 1.20.4 and KSP 12.12.3

I am able to replicate this each time, checked that I'm not using incompatible mods, and have been able to record it. [Recording is here.](https://youtu.be/O1kfzDlJujY)

Steps to reproduce:
- Have ship with monoprop and a kerbal with a full jetpack.
-- Jetpack: 5/5 monoprop. Ship: 90/90 monoprop.
- Use some monoprop on the ship to replicate normal usage, as it only occurs when there's space in the ship tanks for the jetpack monoprop to go.
-- Jetpack: 5/5 monoprop. Ship: 80/90 monoprop.
- Exit ship to go on EVA with Jetpack.
-- Jetpack: 5/5 monoprop. Ship: 80/90 monoprop.
- Enter ship without even having used the jetpacks.
-- Jetpack: 0/5 monoprop. Ship: 85/90 monoprop.
- Exit ship again to go on EVA with jetpack.
-- Jetpack: 0/5 monoprop. Ship: 85/90 monoprop.

**Comment by gotmachine** [comment] 2022-08-14 07:31
Ok. So turns out that we're both right. The MP is actually transferred (if you look at the jetpack cargo part tooltip, it is here). But KSP fails to register it as an available resource.

As a workaround, you can quicksave/quickload to have the MP on the jetpack being correctly registered.

**Closed** 2022-08-14 07:57 UTC
Labels: bug, code
