### ISSUE TITLE
(Realism Overhaul / RP-1) Switching to a vessel disables fuel cells in all vessels

### ISSUE THREAD

**Issue by raymoo** [Kerbalism/Kerbalism#834] opened 2022-11-01 00:33 UTC
Related issue: https://github.com/KSP-RO/RP-0/issues/1548 (closed for being a Kerbalism issue, which is why I didn't post this issue there)

Kerbalism Version: 3.16
KSP: 1.12.3.3173
Mods: The following + the dependencies that CKAN pulls in
- Kerbalism
- Kerbalism RO Config 1.2.7
- KSPBurst 1.5.5.1
- Realism Overhaul 14.18.1.0
- RO Tanks 2.7.0

I cannot reproduce it with stock and Kerbalism only. It is reproducible in the full RP-1 install, but these are enough. This is a screenshot of the full list of mods, including auto-installed dependencies:
![Screenshot 2022-10-31 190856](https://user-images.githubusercontent.com/5734399/199131890-0ca1b3fb-44fa-442b-b016-e2748b26481e.png)

Log (KSP.log, I did not find output_log.txt): 
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/9905776/KSP.log)

Description:
When switching to a vessel, fuel cells on it and other vessels stop working. This separate from the dumping bug - restarting the fuel cell requires toggling both dump and the fuel cell's main button. It also cannot be worked around by toggling before unload like dumping, because it happens when loading any vessel, not just when loading the vessel with the fuel cell.

Save (first time uploading a save so not sure if this is correct):
[persistent.zip](https://github.com/Kerbalism/Kerbalism/files/9905780/persistent.zip)

Reproduction:
1. Have a vessel with a fuel cell, spare EC capacity to fill up, something that drains EC, and LH2 / LOX (The save game has two such vessels, one in orbit and one on the pad)
2. Have another vessel
3. Switch to the vessel with the fuel cell. Toggle dump and power until you can see the EC charging in the resources window. Also check that hovering over its EC icon in the vessels overview shows "perpetual"
4. Switch to another vessel far enough away to unload the first one
5. Hover over the first vessel's EC icon (it will no longer be perpetual)

It does not happen when going to KSC, but going to KSC and then switching back to the same vessel does trigger it. I also noticed that restarting the fuel cell on one vessel can activate it on the other, but turning it off does not turn it off remotely.

EDIT: Forgot to mention but this happens even when the other vessel does not have a fuel cell. It can be any vessel.

**Comment by gotmachine** [comment] 2023-01-27 15:26
This sounds like it has the same root cause as the dump issues.
The dump settings issue is caused by the setting being shared globally for all vessels. Said otherwise, toggling it (or it being toggled wrongly when a vessel is loaded) results in all vessels using this process to use the wrong dump settings.

This should be fixed by https://github.com/Kerbalism/Kerbalism/commit/d6400a0c3cf8d3db028bdf45f6dfb19f7bf6d3e8

**Closed** 2023-01-28 10:12 UTC
Labels: bug, code

**Comment by FioraAeterna** [comment] 2023-03-05 20:44
As of the latest version of RO+RP1+kerbalism, this does not seem to be fixed. I still have to toggle fuel cells on every launch and load-in (even though they are listed as "Running...") or else my EC drains rapidly.

**Comment by FioraAeterna** [comment] 2023-03-07 05:21
I... haven't actually tested that one. So far almost all my use of fuel cells has been with single capsules, so I'm not sure if I've tried loading out for a long period of time. All I know is that it breaks on load-_in_.
