### ISSUE TITLE
Also take ModuleRestockLaunchClamp into account for PlannerController

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#768] opened 2021-11-09 18:14 UTC
As in Planner.cfg which checks for Module[LaunchClamp].

**Comment by Gordon-Dry** [comment] 2021-11-09 18:27
Stuff like this:
GameData\KerbalismConfig\Support\ReStock.cfg
```
@PART[*]:HAS[@MODULE[ProcessController]:HAS[#resource[?ECGen]],@MODULE[ModuleRestockLaunchClamp]]:NEEDS[ReStock]:AFTER[KerbalismDefault]
{
  %MODULE[PlannerController]
  {
	%title = generator
	%considered = false
  }
}
```

**Comment by Gordon-Dry** [comment] 2021-11-09 22:24
Ah, well, ofc. I forgot. This would be too easy. The code itself also needs to support that module ModuleRestockLaunchClamp.

I will try this patch as a possible workaround:
```
@PART[*]:HAS[@MODULE[ProcessController]:HAS[#resource[?ECGen]],@MODULE[ModuleRestockLaunchClamp]]:NEEDS[ReStock]:AFTER[KerbalismDefault]
{
	%MODULE[PlannerController]
	{
		%title = generator
		%considered = false
	}

	@MODULE[ProcessController]:HAS[#resource[?ECGen]]
	{
		// running = true
		@toggle = true
	}
}

```

**Comment by Gordon-Dry** [comment] 2021-11-09 22:43
Well, that works. But as the PlannerController does not work for ModuleRestockLaunchClamp, only this should do the job for now:
```
@PART[*]:HAS[@MODULE[ProcessController]:HAS[#resource[?ECGen]],@MODULE[ModuleRestockLaunchClamp]]:NEEDS[ReStock]:AFTER[KerbalismDefault]
{
	// %MODULE[PlannerController]
	// {
		// %title = generator
		// %considered = false
	// }

	@MODULE[ProcessController]:HAS[#resource[?ECGen]]
	{
		@toggle = true
	}
}

```

**Comment by gotmachine** [comment] 2022-07-19 10:56
duplicate of #779

**Closed by gotmachine** 2022-07-19 10:56 UTC
