### ISSUE TITLE
SolarPanelFixer module : Solar panels starting out at 94% wear

### ISSUE THREAD

**Issue by lpgagnon** [Kerbalism/Kerbalism#484] opened 2019-08-11 22:36 UTC
Not clear whether this is a Kerbalism or ROKerbalism (or what) issue; DRVeyl suggested starting here.

Using Kerbalism build from https://github.com/Standecco/ROKerbalism/tree/sstu-and-solar, which was built ~3 days ago to match Kerbalism's own sstu-and-solar branch ("using latest" according to Standecco, but specific commit not known).

And using ROKerbalism's kerbalism config, at https://github.com/Standecco/ROKerbalism/commit/f5ee8bbf3a3c6d3e1a19c9b4184b077929171dc2 

(on KSP 1.6.1, with a slew of RP-0-related mods)

The issue: after installing that build, I can launch 1 vessel with functioning solar panels (starting at 0% wear); but the next one I launch has panels that start out at "94% wear".

Once game is in this state, all newly-launched vessels have the same problem, even if I reload an earlier save. Must restart the game to get back to a sane state (for one vessel's worth)

Specific steps:
- start from sane state: reinstall ckan kerbalism, launch game, exit, reinstall ROKerbalism:sstu-and-solar Kerbalism, launch game. Load same before-things-broke quicksave as previous tests
- Add 2 sputnik+solarpanel vessels to KCT queue
- Build, Rollout, Launch the first. wear=0%
- Use Range-safety to clear the pad
- Build, Rollout, Launch the second. wear=94%

Looking at persistent.sfs, both "good" panel and "broken" panel had these:
```
PART { name = RO.EarlyTinySolarPanel
MODULE { name = ModuleDeployableSolarPanel
MODULE { name = ModuleROSolarPanel
MODULE { name = SolarPanelFixer
```

The one noteworthy difference between the good and bad vessel: good vessel's SolarPanelFixer had a sane launchUT; the broken vessel's SolarPanelFixer had `launchUT=-1`

**Comment by gotmachine** [comment] 2019-08-11 22:55
1. The sstu-and-solar branch is barely ready for playtesting with the regular configs, at this point it's pointless to test the ROkerbalism configs.
2. There is no "latest build", we haven't updated the binaries, only released a few test versions on our discord. The binaries present in sstu-and-solar are probably quite old and SHOULD NOT BE USED.
3. ModuleROSolarPanel should be removed from the parts, it is incompatible.
4. The RO timeEfficiencyCurve configs must be removed, and instead added to the SolarPanelFixer module. Regarding the curve configs, note that we use hours for keys instead of 24-h days like the stock panels. This has been discussed with @Standecco but I think he is waiting for us to provide a more stable test build.
5. We are currently reworking our release / build process to provide regular test build of the dev branch, this should come in a week or two.
6. All this being said, I wouldn't be surprised if there are issues caused by KCT, or just issues. I will keep this open, to be reviewed again.

More info on the SolarPanelFixer module [on the wiki](https://github.com/Kerbalism/Kerbalism/wiki/TechGuide-~-PartModules-~-SolarPanelFixer)

**Comment by Gordon-Dry** [comment] 2019-08-11 23:43
I wonder if this patch would work:
```
@PART[*]:HAS[@MODULE[ModuleDeployableSolarPanel]:HAS[@timeEfficCurve[]],@MODULE[SolarPanelFixer]]:NEEDS[RealismOverhaul,Kerbalism]:FINAL
{
	@MODULE[SolarPanelFixer]
	{
		timeEfficCurve
		{
				key[*},* = #$/MODULE[ModuleDeployableSolarPanel]/timeEfficCurve/key[*],*$
				@key[*],* *= 24
		}
	}
	@MODULE[ModuleDeployableSolarPanel]
	{
		-timeEfficCurve { ]
	}
}

```

**Comment by Gordon-Dry** [comment] 2019-08-11 23:50
^typo fix

**Comment by gotmachine** [comment] 2019-08-12 00:07
The timeEfficCurve from the base RO configs are meant to be used with the ModuleROSolarPanel module, which has a custom formula going on. It's used by the ModuleROSolarPanel editor tweakeable and I don't think they can be used in the "normal" way.
My suggestion for ROkerbalism is to either delete them completely, or reuse the base patch from RO (which use custom MM variables to define some kind of "technology tiers") to add balanced efficiency curves.

**Comment by gotmachine** [comment] 2019-08-22 22:15
This is fixed by https://github.com/Kerbalism/Kerbalism/commit/dd962baa9cb500340aff9b015c2b48663c64617d

**Closed by gotmachine** 2019-08-22 22:15 UTC
Labels: bug
