### ISSUE TITLE
NSS/OctoSat-SOAR Continued : ModuleManager error causeed by ScanSat config

### ISSUE THREAD

**Issue by utoxin** [Kerbalism/Kerbalism#477] opened 2019-08-02 18:41 UTC
While trying to troubleshoot an issue with the TweakScale dev, we ran into an issue with what appears to be an interaction between Kerbalism and SCANsat. They said to forward this to you.

All details, including my KSP.log and a CKAN export of my installed mods are available in the issue on the TweakScale github. https://github.com/net-lisias-ksp/TweakScale/issues/66

`[ERR 2019-07-31 08:39:53.166] Error - Cannot parse variable search when inserting new key ec_rate = #$../MODULE[ModuleSCANresourceScanner]/RESOURCE[ElectricCharge]/rate$

<cut>

[WRN 2019-07-31 08:40:03.660] Errors in patch prevents the creation of the cache
[LOG 2019-07-31 08:40:03.762] ModuleManager: 15692 patches applied, found <color=orange>1 error</color>
1 error related to GameData/Kerbalism/Support/SCANsat.cfg`

**Comment by UsernamesAreAlwaysTaken** [comment] 2019-08-03 10:54
There should be a filename in that log, or at least the directory of the patch that's causing the errors.

Can I have that please?

**Comment by utoxin** [comment] 2019-08-03 14:25
Dug through the ModuleManager.log, and I /THINK/ this might be the bit you need?

[LOG 2019-07-31 17:20:20.335] Applying update Kerbalism/Support/SCANsat/@PART[*]:HAS[@MODULE[ModuleSCANresourceScanner],@MODULE[KerbalismScansat]]:NEEDS[FeatureScience]:AFTER[zzzKerbalism] to NSS/Parts/OctoSat_Sc_M900.cfg/PART
[ERR 2019-07-31 17:20:20.335] Error - Cannot parse variable search when inserting new key ec_rate = #$../MODULE[ModuleSCANresourceScanner]/RESOURCE[ElectricCharge]/rate$

**Comment by utoxin** [comment] 2019-08-03 14:27
If it'll help you, this is my CKAN mod set.

[Utoxin.zip](https://github.com/Kerbalism/Kerbalism/files/3463913/Utoxin.zip)

And here's a few logs...

[ModuleManager.log](https://github.com/Kerbalism/Kerbalism/files/3463914/ModuleManager.log)
[MMPatch.log](https://github.com/Kerbalism/Kerbalism/files/3463916/MMPatch.log)
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/3463917/KSP.log)

**Comment by UsernamesAreAlwaysTaken** [comment] 2019-08-03 16:41
After a bunch of digging, the problem is in how linux configured that part.

All scansat resource scanners have this bit:
```
	MODULE
	{
		name = ModuleSCANresourceScanner
	...
		RESOURCE
		{
			name = ElectricCharge
			rate = 0.4
		}
	}
```
All of them use Electric charge, which is defined as shown above.

On the other hand, linux has this 
(in https://github.com/linuxgurugamer/NSS/blob/master/GameData/NSS/MM/NSS_MM_ScanSat.cfg)

```
	MODULE
	{
		name = ModuleSCANresourceScanner
       ...
		power = 0.5
	}
```
He uses power for some reason. I have no idea if it even works. This is the only part that has it configurred this way. I assume it's either an oversight, or he did something in the plugin to use power instead of the stock resource definitions.

First attempt should be to contact him and let him know, see if it's intentional. If it is, I'll change the patch, but without confirmation, I have no reason to.

**Comment by utoxin** [comment] 2019-08-03 16:44
LOL. Okay. My bugfix scavenger hunt continues. Thanks for looking into it. I'll reach out to him, and see what he says.

**Comment by UsernamesAreAlwaysTaken** [comment] 2019-08-03 16:45
I'll leave the issue open, waiting on an update. 
Please comment on this again when you know morre.

Thanks

**Comment by linuxgurugamer** [comment] 2019-08-14 17:59
Just an FYI, that error in the file (In NSS Octosat) is from the original mod, I'm pretty sure I didn't do that.  If the only change is to make it "rate" instead of "power", I'll do it myself, I'm in the middle of making some updates to the mod anyway, so it's very timely

**Comment by linuxgurugamer** [comment] 2019-08-14 18:13
How urgent is this needed?  I can push a quickie, but would like to wait a few days to finish the other changes

**Comment by utoxin** [comment] 2019-08-14 20:12
Not a huge deal for me. I wasn't actively using the parts yet in any ships.

**Comment by UsernamesAreAlwaysTaken** [comment] 2019-08-14 20:24
@linuxgurugamer yes, the only change needed is to change 

```
power = 0.5
```
to
```
		RESOURCE
		{
			name = ElectricCharge
			rate = 0.5
		}
```
The error is not criritcal, it's just MM saying it can't find what I ask it to due to the inconsistency. The part itself remains unchanged, but the error prevent the creation of the config cache. That's about it.

**Comment by linuxgurugamer** [comment] 2019-08-16 18:27
Ok, I've fixed it, will be available in the next release, probably in a week or so

**Comment by linuxgurugamer** [comment] 2019-08-17 23:29
I just made a release which includes a fix for this

**Comment by gotmachine** [comment] 2019-08-17 23:31
@linuxgurugamer Great, thanks for updating us.
@UsernamesAreAlwaysTaken I will let you close this.

**Closed** 2019-08-17 23:59 UTC
Labels: bug, mod support
