### ISSUE TITLE
Pressure control - inconsistent nitrogen consumption

### ISSUE THREAD

**Issue by tonimark** [Kerbalism/Kerbalism#381] opened 2019-04-13 08:51 UTC
I realize on not resized modules when I warp fast (more that 100000x) one of my gravity rings, got smaller and lost some % of habitat this has as results extreme amounts of nitrogen wasted and least only for a few days while it was planned and calculated to least for more than 2 years, if you need any information to inform me.

**Comment by gotmachine** [comment] 2022-07-24 13:01
Duplicate of #766

**Closed by gotmachine** 2022-07-24 13:01 UTC
Labels: bug
