### ISSUE TITLE
Cannot gather samples from comets

### ISSUE THREAD

**Issue by Jakeyjuju** [Kerbalism/Kerbalism#689] opened 2020-11-10 21:03 UTC
I've managed to reach a comet and whenever I right click on it as a kerbal and select the "take surface sample" option nothing happens. The log file shows this each time:
[EXC 20:55:40.711] NullReferenceException: Object reference not set to an instance of an object
	ModuleComet.performSampleExperiment (ModuleScienceContainer collector) (at <c1858a3f77504bd1aaa946fdccf84670>:0)
	ModuleComet.TakeSampleEVAEvent () (at <c1858a3f77504bd1aaa946fdccf84670>:0)
	BaseEvent.Invoke () (at <c1858a3f77504bd1aaa946fdccf84670>:0)
	UIPartActionButton.OnClick () (at <c1858a3f77504bd1aaa946fdccf84670>:0)
	UnityEngine.Events.InvokableCall.Invoke () (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
	UnityEngine.Events.UnityEvent.Invoke () (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
	UnityEngine.UI.Button.Press () (at <99c70f3212f546f499a5c598b1663bb9>:0)
	UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <99c70f3212f546f499a5c598b1663bb9>:0)
	UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <99c70f3212f546f499a5c598b1663bb9>:0)
	UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <99c70f3212f546f499a5c598b1663bb9>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.EventSystems.EventSystem:Update()

I'm not sure if this is a problem with Kerbalism or another mod, but Kerbalism is the only mod I have installed that effects science experiments.

**Comment by gotmachine** [comment] 2020-11-10 21:32
Duplicate of #654

**Closed by gotmachine** 2020-11-10 21:32 UTC
Labels: duplicate
