### ISSUE TITLE
Configured experiments or processes setup disappearing

### ISSUE THREAD

**Issue by EmperorBlackadder** [Kerbalism/Kerbalism#759] opened 2021-10-12 17:53 UTC
Been loving Kerbalism so far but this rly breaks the mod for me. Whenever I launch a new craft, with either a lab experiment or a Crew experiment, whenever I launch it fails to show up. At first I thought I had to obey the prerequisite parameters so I did and launched a lab module to low orbit with JAMMED (it didn't show up on Launch pad) once it was in shadow I checked to see if it was available and it still didn't show up.

Then I checked to see if it was a problem with KCT, so I uninstalled KCT on that playthrough and still, nothing.

Then I figured it was because I uninstalled mods mid way through the playthrough, so I launched a new game in sandbox mode to test, loaded up a Hitchhiker container with 2 kerbals and configured it with FLOAT, cheated into low orbit and still, it didn't show up.

I've been looking around everywhere to see if anyone else has had this problem and I'm going crazy because it seems like no one else does.

**Comment by Synergy192** [comment] 2021-10-18 12:05
Also having this issue on KSP 1.10.1 with Kerbalism 3.14

**Comment by d-south** [comment] 2021-11-01 18:26
I'm having the same issue. I noticed after some time in a mod-heavy career playthrough that all crewed and lab experiment modules are disappearing at vehicle launch, with only one exception (the 5m SSPX lab). I replicated the issue in a brand new sandbox save. I have no idea why this is, but I've attached my KSP.log in case it reveals anything.

I did notice that the log spits out this error for the "Configure" module:
`[WRN 13:57:18.264] ...Configure module found at index 5.
[WRN 13:57:18.265] [Part]: PartModule indexing mismatch at Large.Crewed.Lab, index 27.`

[KSP.log](https://github.com/Kerbalism/Kerbalism/files/7455372/KSP.log)

**Comment by gotmachine** [comment] 2021-11-01 19:12
Kerbalism is especially sensitive to part config changes. 
In other words, you should avoid installing/uninstalling (and even updating) mods in an existing Kerbalism save.

If you notice "indexing mismatch" entries in your log, it will cause Configure module setups to be lost. It can happen after launching a saved craft, or after loading an unloaded vessel.

Contrary to popular belief, KSP isn't able to handle correctly a part config change where modules are added/removed.
Specifically, it isn't able to "reconnect" modules to their persisted data when multiple occurences of the same module exist on a part, causing the persisted data to be either lost or assigned to the wrong module.

 I won't attempt to fix it in Kerbalism, this is a more general KSP issue that also affect other mods. I'm working on a fix in KSPCommunityFixes, more details here : https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/14

This being said, I don't exclude the possibility of a configure module bug.

**Comment by gotmachine** [comment] 2021-11-01 19:13
For the record, another report by @jessicest : 

The problem: Crafts in flight sometimes lose all of their lab experiments (CHILLED/JAMMED/etc) and their Crew experiments (FLOAT/FLIGHT/LEAVE/etc).

I don't yet know how to reproduce this.

It's happened at least twice in my current save, and this thread talks about a kerbalism game in which the same issue is happening (search for "save file" to find multiple occurrences): https://forum.kerbalspaceprogram.com/index.php?/topic/196959-kerbalism-space-program/

Luckily I have a backup of my KSP folder from before the issue occurred, so we can dig into the change in symptoms.

Here's an interesting point: if we compare the contents of `persistent.sfs` before and after the loss of experiments, by restricting our search to changed `cfg =` lines in the vessel called `t6c wax tadpole`, something specific has happened:

before:

```
					cfg = "$None%LEAVE
					cfg = "$None&FLIGHT
					cfg = "$None&FLIGHT
					cfg = "$None&FLIGHT
					cfg = "%FLOAT'HERRING
					cfg = "&FLIGHT%STAKE
					cfg = "'CHILLED&JAMMED
					cfg = "8Fish Species Observation3Materials Bay Study
```

after:

```
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
					cfg = "(Scrubber0Pressure Control
```

It seems to me that the `Configure` modules all lost their configuration and reverted to scrubber/pressure mode.

KSP version (before & after): `1.12.2.3167 (WindowsPlayer x64)`
Kerbalism version (before & after): `"VERSION": {"MAJOR": 3, "MINOR": 14, "PATCH": 0, "BUILD": 0},`

Attached files from before the issue happened:

 - [installed_mods_before.txt](https://github.com/Kerbalism/Kerbalism/files/7447878/installed_mods_before.txt)
 - [persistent_before.zip](https://github.com/Kerbalism/Kerbalism/files/7447881/persistent_before.zip)

Attached files from after the issue happened (this is 21 days later; idk when it actually occurred):

 - [persistent.zip](https://github.com/Kerbalism/Kerbalism/files/7447871/persistent.zip)
 - [installed_mods_after.txt](https://github.com/Kerbalism/Kerbalism/files/7447858/installed_mods_after.txt)
 - [Player.zip](https://github.com/Kerbalism/Kerbalism/files/7447868/Player.zip) -- i assume this isn't actually useful as the issue has already occurred

I haven't actually trimmed down to minimal mods and attempted to reproduce the issue as the contributing instructions suggest; mostly because I don't know how to reproduce it! But I'm happy to attempt to reproduce it once we have some ideas of what might trigger it. My hunch is that it's from installing/uninstalling mods but that's a wild guess.

**Comment by d-south** [comment] 2021-11-10 03:49
I have been tweaking with the modlist somewhat and found that the lab modules issue may be something else entirely (unrelated to adding/removing mods). I trimmed my modlist somewhat and added KSPCommunityFixes to see if its fix would have any effect. I still experienced the lab/crew experiment modules disappearing on a new save. Specifically, I built a vessel containing the lab/crew modules (MPL 2 & Hitchhiker) in the VAB, added experiments, and found that they were invariably gone on the launchpad. My changes to the Configure modules seem to have no effect on this, as the modules invariably default to Scrubber+Pressure each time.

My log:
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/7509670/KSP.log)
My current modlist:
[1.12.2 Modlist.txt](https://github.com/Kerbalism/Kerbalism/files/7509674/1.12.2.Modlist.txt)

**Comment by jessicest** [comment] 2021-11-10 07:51
Thank you @gotmachine for looking into this!

I've [added to the documentation](https://github.com/Kerbalism/Kerbalism/wiki/Home-~-Mod-Support/_compare/11929455e46cac7499bf4edc46e549c145cd8397...a5f49eeac3d034367998f1e38a24c325670e9542) about this so that players can plan around it, as it's devastating to multi-year science missions (which are one of Kerbalism's most awesome features!)

>  Specifically, it isn't able to "reconnect" modules to their persisted data when multiple occurences of the same module exist on a part, causing the persisted data to be either lost or assigned to the wrong module.

If I'm understanding you correctly (and it's entirely possible that I'm not), then does it mean we're only experiencing this issue on parts with configurable science because they have `Configure` modules for both their science and their life support? (If so, then my documentation update is slightly wrong.)

But also: if that's the case, couldn't we rename the science configuration modules so they don't share a name with the life support configuration modules?

**Comment by gotmachine** [comment] 2021-11-10 08:25
@jessicest There are some workarounds that could be implemented, but this issue also affect any other modules that exist in multiple instances (process controllers, experiments, reliability...), so this would require a lot of changes. Moreover, such fixes would break existing saves. In any case, I don't have plans to work on that.

@d-south I'm unable to reproduce. Unless you are talking about launching a ship that was saved prior to a mod config change, in which case, yes, the described issue applies. Also, the KSPCommunityFixes version that you are using (1.0.4) doesn't contain the indexing mismatch fix, I added that in the 1.1.0 pre-release : https://github.com/KSPModdingLibs/KSPCommunityFixes/releases/tag/1.1.0

**Comment by d-south** [comment] 2021-11-12 01:48
@gotmachine The issue appears to have been resolved with the newest build of KSPCommunityFixes. The Hitchhiker and MPL appear to be holding onto configurations between loads now.

**Comment by jessicest** [comment] 2021-11-16 09:03
Thanks @gotmachine. I can further update the docs if this is helpful. Would it be correct if they say this? (I'm guessing a bit.)

> If you have existing kerbalism flights in progress and you'd like to update or switch up your mods, here's how to minimize the risk of losing your science configurations:
> 1) install KSPCommunityFixes, version 1.2.0 or later
> 2) load each of your in-flight vessels that have Kerbalism science experiments
> 3) save and quit the game
> 4) now, it should be safe to update, install, or remove mods without messing up your ships in flight.

**Comment by gotmachine** [comment] 2021-11-16 09:28
@jessicest No, the steps you describe won't do anything. Also, the KSPCommunityFixes patch doesn't make config changes 100% safe, it replace the stock "module index reconnection" logic with one that do a better job, but there are still corner cases that fundamentally can't be covered.

This being said, reloading every in-flight vessel is indeed recommended **following a config change**, as this is the only way to update their persisted state so it match the new configs state (and this apply no matter if KSPCommunityFixes is installed or not). If you don't do that, every time a config change happen, the persisted state will be more and more de-synchronized, increasing the probability of a "non-recoverable" indexing mismatch.

But frankly, "breaking" config changes are usually caused by a mod installation/uninstallation, this is the main thing you should avoid. While a mod update can contain a config change, this is relatively uncommon.

So my recommendations would be  :
- Install KSPCommunityFixes (which also fix a few other annoying issues that affect Kerbalism)
- Don't remove/add mods in an existing save
- If you do it anyway, the next time you launch KSP, load every in-flight vessel you care about.

**Comment by gotmachine** [comment] 2022-07-24 13:15
KSPCommunityFixes is now marked as a dependency for Kerbalism. 
This should make that issue quite rare in practice.

For the record, a 100% safe fix can only be achieved by implementing specific handling in the configure module, either with a custom implementation or by leveraging the [MultipleModuleInPart API](https://github.com/KSPModdingLibs/KSPCommunityFixes/wiki/MultipleModuleInPartAPI) from KSPCF.

**Closed by gotmachine** 2022-07-24 13:15 UTC
Labels: bug, cfg, code, can't fix on our side
