### ISSUE TITLE
NRE & game freeze in VesselData.FieldsDefaultInit

### ISSUE THREAD

**Issue by GarwelGarwel** [Kerbalism/Kerbalism#833] opened 2022-10-20 07:45 UTC
I've been landing a rover on Minmus and had the game soft-freeze (i.e. it slows down and I can't leave the Flight scene, save or go to main menu, but I can interact with the UI) every time it landed. I'm playing a heavily modded game, so there is a lot of stuff going on in the log, but this is how it all started:

```
[LOG 08:56:23.798] [SpaceAge] OnSituationChanged(<'391113 Babakin 14 Minmus', 'SUB_ORBITAL', 'LANDED'>)
[LOG 08:56:23.893] Decoupler.0 Exploded!! - blast awesomeness: 0.5
[LOG 08:56:23.898] [SpaceAge] OnSituationChanged(<'', '0', 'LANDED'>)
[ERR 08:56:23.900] Exception handling event onVesselCreate in class CollectScienceCustom:System.NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.VesselData.FieldsDefaultInit (ProtoVessel pv) [0x000a8] in <94f72890f68a4c62b6331661aa032e5e>:0 
  at KERBALISM.VesselData..ctor (Vessel vessel) [0x000f9] in <94f72890f68a4c62b6331661aa032e5e>:0 
  at KERBALISM.DB.KerbalismData (Vessel vessel) [0x00014] in <94f72890f68a4c62b6331661aa032e5e>:0 
  at KERBALISM.SolarPanelFixer.OnSave (ConfigNode node) [0x00041] in <94f72890f68a4c62b6331661aa032e5e>:0 
  at PartModule.Save (ConfigNode node) [0x00131] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at ProtoPartModuleSnapshot..ctor (PartModule module) [0x000d2] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at ProtoPartSnapshot..ctor (Part PartRef, ProtoVessel protoVessel, System.Boolean preCreate) [0x00420] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at ProtoPartSnapshot..ctor (Part PartRef, ProtoVessel protoVessel) [0x00000] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at ProtoVessel..ctor (Vessel VesselRef, System.Boolean preCreate) [0x001e3] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at ProtoVessel..ctor (Vessel VesselRef) [0x00000] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at ContractConfigurator.Extensions+<GetHashes>d__5.MoveNext () [0x0003f] in <474f0790e8a04162b3548abced716556>:0 
  at ContractConfigurator.Parameters.VesselParameter.OnVesselCreate (Vessel vessel) [0x00099] in <474f0790e8a04162b3548abced716556>:0 
  at EventData`1[T].Fire (T data) [0x000b0] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 

[EXC 08:56:23.901] NullReferenceException: Object reference not set to an instance of an object
	KERBALISM.VesselData.FieldsDefaultInit (ProtoVessel pv) (at <94f72890f68a4c62b6331661aa032e5e>:0)
	KERBALISM.VesselData..ctor (Vessel vessel) (at <94f72890f68a4c62b6331661aa032e5e>:0)
	KERBALISM.DB.KerbalismData (Vessel vessel) (at <94f72890f68a4c62b6331661aa032e5e>:0)
	KERBALISM.SolarPanelFixer.OnSave (ConfigNode node) (at <94f72890f68a4c62b6331661aa032e5e>:0)
	PartModule.Save (ConfigNode node) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	ProtoPartModuleSnapshot..ctor (PartModule module) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	ProtoPartSnapshot..ctor (Part PartRef, ProtoVessel protoVessel, System.Boolean preCreate) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	ProtoPartSnapshot..ctor (Part PartRef, ProtoVessel protoVessel) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	ProtoVessel..ctor (Vessel VesselRef, System.Boolean preCreate) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	ProtoVessel..ctor (Vessel VesselRef) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	ContractConfigurator.Extensions+<GetHashes>d__5.MoveNext () (at <474f0790e8a04162b3548abced716556>:0)
	ContractConfigurator.Parameters.VesselParameter.OnVesselCreate (Vessel vessel) (at <474f0790e8a04162b3548abced716556>:0)
	EventData`1[T].Fire (T data) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	EventData`1:Fire(Vessel)
	Vessel:Initialize(Boolean, Boolean, Boolean, Boolean)
	Vessel:Initialize(Boolean)
	Part:Part.decouple_Patch4(Part, Single)
	Part:Part.Die_Patch3(Part)
	Part:explode(Single)
	Part:explode()
	Part:HandleCollision(Collision)
	Part:CheckCollision(Collision)
	Part:OnCollisionEnter(Collision)
```

Then the whole log is just endless NRE in the same method, VesselData.FieldsDefaultInit.

I play with Kerbalism reliability and malfunctions highlight on, but engine malfunctions off.

**Comment by jmburbach** [comment] 2022-10-21 03:49
I've also been experiencing what appears to be the same thing recently when trying to do some base building. When I dock/undock (mostly undocking seems to trigger it) the base modules on the surface I get these errors and usually need to kill the game as nothing works anymore.

**Comment by gotmachine** [comment] 2022-11-10 20:12
The issue is caused by ContractConfigurator. It creates the ProtoVessel object for the new Vessel before that new Vessel is fully initialized by KSP, which is very sketchy behavior to say the least.

Specifically, the issue is here : 
https://github.com/jrossignol/ContractConfigurator/blob/7015264e285f00d4d2772888d8b9e1d992b34fc1/source/ContractConfigurator/Util/Extensions.cs#L130

This being said, and because from a quick look I have some doubts this can easily be fixed on the CC side, we should try to handle this issue from the Kerbalism side.

**Comment by jmburbach** [comment] 2022-11-11 15:51
Thanks for having a look. I've removed ContractConfigurator now but I still get exceptions apparently stemming from FieldsDefaultInit. I suspect in my case it has something to do with some combination of ground anchors and/or extraplanetary launchpads and/or docking/undocking to those things. I'll have to try and dig deeper to see if I can find a simple repeatable example of the issue when I get time.

In any case it seems it's not just ContractConfigurator, but also other mods or maybe even weird stock behavior with ground anchors or something that can end up triggering the same issue. 

`[EXC 10:29:56.758] NullReferenceException: Object reference not set to an instance of an object
    KERBALISM.VesselData.FieldsDefaultInit (ProtoVessel pv) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.VesselData..ctor (Vessel vessel) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.DB.KerbalismData (Vessel vessel) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.SolarPanelFixer.OnSave (ConfigNode node) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    PartModule.Save (ConfigNode node) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
    ProtoPartModuleSnapshot..ctor (PartModule module) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
    ProtoPartSnapshot..ctor (Part PartRef, ProtoVessel protoVessel, System.Boolean preCreate) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
    ProtoPartSnapshot..ctor (Part PartRef, ProtoVessel protoVessel) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
    ProtoVessel..ctor (Vessel VesselRef, System.Boolean preCreate) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
    Vessel.Initialize (System.Boolean fromShipAssembly, System.Boolean preCreate, System.Boolean orbiting, System.Boolean setActiveVessel) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
    Vessel.Initialize (System.Boolean fromShipAssembly) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
    (wrapper dynamic-method) Part.Part.Undock_Patch2(Part,DockedVesselInfo)
    ModuleDockingNode.Undock () (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
    BaseEvent.Invoke () (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
    UIPartActionButton.OnClick () (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
    UnityEngine.Events.InvokableCall.Invoke () (at <2425394cf09642369e2109953e31f62b>:0)
    UnityEngine.Events.UnityEvent.Invoke () (at <2425394cf09642369e2109953e31f62b>:0)
    UnityEngine.UI.Button.Press () (at <e15fd066925c43a8a8f645414da73acb>:0)
    UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <e15fd066925c43a8a8f645414da73acb>:0)
    UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e15fd066925c43a8a8f645414da73acb>:0)
    UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e15fd066925c43a8a8f645414da73acb>:0)
    UnityEngine.DebugLogHandler:LogException(Exception, Object)
    ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
    UnityEngine.EventSystems.EventSystem:Update()
[EXC 10:29:56.794] NullReferenceException: Object reference not set to an instance of an object
    KERBALISM.VesselData.FieldsDefaultInit (ProtoVessel pv) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.VesselData..ctor (Vessel vessel) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.DB.KerbalismData (Vessel vessel) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.Reliability.Highlight (Part p) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.Reliability.Update () (at <94f72890f68a4c62b6331661aa032e5e>:0)
    UnityEngine.DebugLogHandler:LogException(Exception, Object)
    ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
    UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 10:29:56.797] NullReferenceException: Object reference not set to an instance of an object
    KERBALISM.VesselData.FieldsDefaultInit (ProtoVessel pv) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.VesselData..ctor (Vessel vessel) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.DB.KerbalismData (Vessel vessel) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.Reliability.Highlight (Part p) (at <94f72890f68a4c62b6331661aa032e5e>:0)
    KERBALISM.Reliability.Update () (at <94f72890f68a4c62b6331661aa032e5e>:0)
    UnityEngine.DebugLogHandler:LogException(Exception, Object)
    ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
    UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

**Comment by AidanBrem** [comment] 2022-11-11 18:39
Don’t have logs at this time, but anecdotally this only happens on the ground - I have a bug with undocking with KAS parts, and I’ve only actually noticed it when both vessels would begin landed on the ground.

**Closed** 2023-01-28 10:51 UTC
Labels: bug
